### PR TITLE
CI: test ci

### PR DESCRIPTION
**Pull request by P0TER**

### CODE REVIEW

**Review by ZadorozhnyiYevhenii — APPROVED** [review]

**Comment by P0TER** [comment]
This PR is included in version 1.0.0 :tada:

**Comment by P0TER** [comment]
This pull request is included in version 1.0.0

**Comment by P0TER** [comment]
This pull request is included in version 1.0.0

**Comment by P0TER** [comment]
This pull request is included in version 1.0.0 :tada:

**Comment by P0TER** [comment]
This pull request is included in version 1.0.0 :tada:

**Pull request merged**
